<a href="https://colab.research.google.com/github/darshilnagle7-create/numpy_assignment/blob/main/Class1file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [ ]:
pip install numpy


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
import numpy as np
l = [10,20,30,40,50] #1D array(vector)
array = np.array(l)
print(array)


[10 20 30 40 50]


Lets create a matrix using list

In [ ]:
a = [[1,2,3] ,
    [4,5,6] ,
    [7,8,9]]

matrix = np.array(a)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [ ]:
# np.zeros()
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
#np.zeros() for metrix
#rows and columns
np.zeros([3,4]) # rows , columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.ones() for metrix
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full(5,7) # space , values

array([7, 7, 7, 7, 7])

In [ ]:
np.full([3,3],7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
 #np.arange()
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [ ]:
#np.eye() # Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#np.linspace() # start = 0,stop = 1, value = 5
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#np.random.rand()
np.random.rand(3,3)


array([[0.37687696, 0.70782396, 0.74258446],
       [0.56621282, 0.05108341, 0.4809332 ],
       [0.62265161, 0.8480265 , 0.244429  ]])

In [ ]:
# np.random.randint
np.random.randint(0,10,2),[3,3] #


(array([7, 9]), [3, 3])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution