<a href="https://colab.research.google.com/github/darshilnagle7-create/numpy_assignment/blob/main/class3file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [ ]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

#1.Addition of the arrays
print(a+b)

#2.Substraction of the arrays
print(a-b)

#3.Multiplication of the arrrays
print(a*b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [ ]:
a = np.array([10,20,30,40])
print(a*5)

[ 50 100 150 200]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [ ]:
A = np.array([[10,20,30],
              [40,50,60]])

B = np.array([10,20,30])

print(A+B)

[[20 40 60]
 [50 70 90]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [ ]:
# Basic statistical operations perform
arr = np.array([4,78,21,34,100,56])
#1.sum
print(f"Sum is : {arr.sum()}")

#2.mean
print(f"Mean(average) is:{arr.mean()}")

#3.Min
print(f"min is : {arr.min()}")

#4.Max
print(f"max is : {arr.max()}")

#5.Standard deviation
print(f"Standard deviation :{arr.std()}")

#6.Varaiance
print(f"Variance : {arr.var()}")

Sum is : 293
Mean(average) is:48.833333333333336
min is : 4
max is : 100
Standard deviation :32.97684372741306
Variance : 1087.4722222222224


You can also do the axis based operations row-Wise and Colum-wise

In [ ]:
data = np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])
print(f"sum of all: {data.sum()}")
#axis = 0-> columns
#axis = 1 -> rows
print(f"sum of columns : {np.sum(data, axis = 0)}")
print(f"sum of rows : {np.sum(data, axis = 1)}")

sum of all: 45
sum of columns : [12 15 18]
sum of rows : [ 6 15 24]
