<a href="https://colab.research.google.com/github/darshilnagle7-create/numpy_assignment/blob/main/class4file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50,60])

#Pick element at position 0,2,4
arr[[0,2,4]]

array([10, 30, 50])

You can do this fancy indexing in 2D Matrix aswell

In [ ]:
import numpy as np
matrix = np.arange(1,13).reshape(3,4)
#matrix[[row0,col1],[row1,col2]]
print(matrix)
matrix[[0,1],[1,2]]
matrix[[1,2],[0,2]]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 5, 11])

##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
import numpy as np

arr = np.array([5,7,11,18,30])
#will get the indices only which are greater than 10
np.where(arr > 10)

# arr me jha bhi 10 se choti value aa rhi hai waha 0 se replace ho jayegi.
print(np.where(arr > 10 ,arr , 0))

(array([2, 3, 4]),)

In [ ]:
arr2 = np.array([23,25,30,50,100,75,80])

#replace the value with 0 which are less than 55
print(np.where(arr2  > 55 ,arr2 , 0))

[  0   0   0   0 100  75  80]


##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [ ]:
#Aam zindagi
array = np.array([2,10,56,1,54])
print(np.sort(array))

index = np.argsort(array)
print(index)

[ 1  2 10 54 56]
[3 0 1 4 2]


In [ ]:
# Matrix sort
matrix = np.array([[4,3,12],[14,15,10]])
#1.Row wise sort(axis = 1)
np.sort(matrix, axis =1)


#2.Colum wise sort(axis = 0)
np.sort(matrix,axis = 0)

#3.sort comple

array([[ 4,  3, 10],
       [14, 15, 12]])

##Concatenation & Stacking

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [ ]:
A = np.array([[1,2],[4,5]])
B = np.array([[7,8],[10,11]])

#Vertical Stacking
np.vstack([A,B])

#Horizonatal Stacking
np.hstack([A,B])

array([[ 1,  2,  7,  8],
       [ 4,  5, 10, 11]])