<a href="https://colab.research.google.com/github/darshilnagle7-create/numpy_assignment/blob/main/numpy_final_assign_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [2]:
# Write your code
import numpy as np
arr = np.array([10,20,30,40,50])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [6]:
# Write your code here
matrix = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [10]:
# Write your code here
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [12]:
# Write your code here
arr = np.array([10,20,30,40,50,60])
print(arr[2:6])

[30 40 50 60]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [17]:
# Write your code here
arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])

[10 30 50]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [20]:
# Write your code here
arr = np.array([7,16,6,25,29,35])

print(arr[arr > 15])


[16 25 29 35]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [22]:
# Write your code here
arr = np.array([1,2,3,4,5])
print(arr+10)

[11 12 13 14 15]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [29]:
# Write your code here
arr = np.array([1,2,3,4,5])
print(f"sum of array : {arr.sum()}")
print(f"mean of array : {arr.mean()}")
print(f"max of array : {arr.max()}")
print(f"min of array : {arr.min()}")

sum of array : 15
mean of array : 3.0
max of array : 5
min of array : 1



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [30]:
# Write your code here
arr = np.array([9,5,10,4,7,1])
np.sort(arr)

array([ 1,  4,  5,  7,  9, 10])


# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [35]:
# Write your code here
arr1 = [1,2,3,4]
arr2 = [5,6,7,8]
print(np.concatenate([arr1,arr2]))

[1 2 3 4 5 6 7 8]


In [36]:
np.vstack([arr1,arr2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])